export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS';
export const SEARCH_PRODUCTS_ERROR = "SEARCH_PRODUCTS_ERROR"
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const NEW_PRODUCT = 'NEW_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const SET_PAGE_NUMBER = 'SET_PAGE_NUMBER';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_SUBCATEGORIES = 'FETCH_SUBCATEGORIES';
export const SET_SELECTED_CATEGORIES = 'SET_SELECTED_CATEGORIES';
export const SET_SELECTED_SUBCATEGORIES = 'SET_SELECTED_SUBCATEGORIES';
export const SET_FILTER_CONDITION = 'SET_FILTER_CONDITION';